echo 'Installing packages'
sudo apt-get update
sudo apt-get install p7zip-full
sudo add-apt-repository ppa:otto-kesselgulasch/gimp
sudo apt-key adv --fetch-keys http://repos.codelite.org/CodeLite.asc
sudo echo 'deb  http://repos.codelite.org/ubuntu/ precise universe' >> /etc/apt/sources.list
sudo wget -q http://www.webmin.com/jcameron-key.asc
sudo apt-key add jcameron-key.asc
sudo echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu precise main" | tee /etc/apt/sources.list.d/webupd8team-java.list
sudo echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu precise main" | tee -a /etc/apt/sources.list.d/webupd8team-java.list
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EEA14886
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EEA14886
sudo apt-get update
sudo apt-get install oracle-java7-installer -y
sudo apt-get install abiword -y
sudo apt-get install accountsservice -y
sudo apt-get install ace-of-penguins -y
sudo apt-get install acl -y
sudo apt-get install acpid -y
sudo apt-get install acpi-support -y
sudo apt-get install activity-log-manager-common -y
sudo apt-get install activity-log-manager-control-center -y
sudo apt-get install adduser -y
sudo apt-get install adium-theme-ubuntu -y
sudo apt-get install aggregate -y
sudo apt-get install aisleriot -y
sudo apt-get install akonadi-backend-mysql -y
sudo apt-get install akonadi-server -y
sudo apt-get install akregator -y
sudo apt-get install alacarte -y
sudo apt-get install alpine-doc -y
sudo apt-get install alpine -y
sudo apt-get install alsa-base -y
sudo apt-get install alsa-utils -y
sudo apt-get install amarok-common -y
sudo apt-get install amarok-utils -y
sudo apt-get install amarok -y
sudo apt-get install anacron -y
sudo apt-get install antlr3 -y
sudo apt-get install ant-optional -y
sudo apt-get install ant -y
sudo apt-get install apache2.2-bin -y
sudo apt-get install apache2.2-common -y
sudo apt-get install apache2-mpm-prefork -y
sudo apt-get install apache2-utils -y
sudo apt-get install apache2 -y
sudo apt-get install apg -y
sudo apt-get install apparmor -y
sudo apt-get install app-install-data-partner -y
sudo apt-get install app-install-data -y
sudo apt-get install appmenu-gtk3 -y
sudo apt-get install appmenu-gtk -y
sudo apt-get install appmenu-qt -y
sudo apt-get install apport-gtk -y
sudo apt-get install apport-kde -y
sudo apt-get install apport-symptoms -y
sudo apt-get install apport -y
sudo apt-get install apt-utils -y
sudo apt-get install aqemu -y
sudo apt-get install ark -y
sudo apt-get install arptables -y
sudo apt-get install aspectj -y
sudo apt-get install aspell-en -y
sudo apt-get install aspell -y
sudo apt-get install at-spi2-core -y
sudo apt-get install at -y
sudo apt-get install bash-completion -y
sudo apt-get install bash -y
sudo apt-get install brasero -y
sudo apt-get install byobu -y
sudo apt-get install bzip2 -y
sudo apt-get install cabextract -y
sudo apt-get install catfish -y
sudo apt-get install cdparanoia -y
sudo apt-get install cdrdao -y
sudo apt-get install codeblocks -y
sudo apt-get install codelite -y
sudo apt-get install compiz -y
sudo apt-get install cpp -y
sudo apt-get install curl -y
sudo apt-get install diffutils -y
sudo apt-get install doxygen -y
sudo apt-get install empathy -y
sudo apt-get install expect -y
sudo apt-get install filezilla -y
sudo apt-get install fping -y
sudo apt-get install ftp -y
sudo apt-get install fuse -y
sudo apt-get install galculator -y
sudo apt-get install gcalctool -y
sudo apt-get install gcc -y
sudo apt-get install gdb -y
sudo apt-get install gedit -y
sudo apt-get install geoip-database -y
sudo apt-get install gimp -y
sudo apt-get install git -y
sudo apt-get install gjs -y
sudo apt-get install gns3 -y
sudo apt-get install grub-customizer -y
sudo apt-get install guake -y
sudo apt-get install gzip -y
sudo apt-get install html2text -y
sudo apt-get install htop -y
sudo apt-get install lynx -y
sudo apt-get install mc -y
sudo apt-get install minicom -y
sudo apt-get install mysql-server -y
sudo apt-get install nano -y
sudo apt-get install nautilus -y
sudo apt-get install nmap -y
sudo apt-get install ntfs-3g -y
sudo apt-get install p7zip-full -y
sudo apt-get install p7zip -y
sudp apt-get install pev -y
sudo apt-get install php5 -y
sudo apt-get install php5-gd -y
sudo apt-get install putty-tools -y
sudo apt-get install putty -y
sudo apt-get install python -y
sudo apt-get install qemu -y
sudo apt-get install rar -y
sudo apt-get install samba -y
sudo apt-get install sshfs -y
sudo apt-get install tftpd -y
sudo apt-get install tftp -y
sudo apt-get install transmission -y
sudo apt-get install unp -y
sudo apt-get install unrar -y
sudo apt-get install undms -y
sudo apt-get install unace -y
sudo apt-get install unzip -y
sudo apt-get install vinagre -y
sudo apt-get install virtualbox -y
sudo apt-get install vlan -y
sudo apt-get install vnc4server -y
sudo apt-get install webalizer -y
sudo apt-get install webmin -y
sudo apt-get install wine -y
sudo apt-get install wireshark -y
sudo apt-get install wkhtmltopdf
sudo apt-get install xscreensaver-data -y
sudo apt-get install xscreensaver-gl -y
sudo apt-get install xscreensaver -y
sudo apt-get install xterm -y
sudo apt-get install zenmap -y
sudo apt-get install zip -y
sudo apt-get install zsh -y
